# Generated by Django 4.2.3 on 2023-07-27 08:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_author_options_alter_post_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscribeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.ManyToManyField(through='main.UserSubscribeCategory', to=settings.AUTH_USER_MODEL),
        ),
    ]
